"""add missing fields to mentorship_request

Revision ID: 1d83e1bc90d7
Revises: e6a90bfef524
Create Date: 2026-06-01 14:07:38.222870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d83e1bc90d7'
down_revision: Union[str, Sequence[str], None] = 'e6a90bfef524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentorship_requests_id'), table_name='mentorship_requests')
    op.drop_table('mentorship_requests')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_mentor_applications_email'), table_name='mentor_applications')
    op.drop_index(op.f('ix_mentor_applications_id'), table_name='mentor_applications')
    op.drop_table('mentor_applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('field_of_expertise', sa.VARCHAR(), nullable=False),
    sa.Column('years_of_experience', sa.INTEGER(), nullable=False),
    sa.Column('linkedin_url', sa.VARCHAR(), nullable=False),
    sa.Column('bio', sa.TEXT(), nullable=False),
    sa.Column('cv_url', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_applications_id'), 'mentor_applications', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_applications_email'), 'mentor_applications', ['email'], unique=1)
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('faculty', sa.VARCHAR(), nullable=True),
    sa.Column('year_of_study', sa.VARCHAR(), nullable=True),
    sa.Column('areas_of_interest', sa.VARCHAR(), nullable=True),
    sa.Column('has_business_idea', sa.VARCHAR(), nullable=True),
    sa.Column('expectations', sa.VARCHAR(), nullable=True),
    sa.Column('skills_to_improve', sa.VARCHAR(), nullable=True),
    sa.Column('motivational_message', sa.TEXT(), nullable=True),
    sa.Column('preferred_session_format', sa.VARCHAR(), nullable=True),
    sa.Column('session_commitment', sa.BOOLEAN(), nullable=True),
    sa.Column('consent_data', sa.BOOLEAN(), nullable=True),
    sa.Column('consent_evaluation', sa.BOOLEAN(), nullable=True),
    sa.Column('cv_url', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=1)
    op.create_table('mentorship_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('expectations', sa.VARCHAR(), nullable=False),
    sa.Column('skills_to_improve', sa.VARCHAR(), nullable=False),
    sa.Column('cv_file_path', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_requests_id'), 'mentorship_requests', ['id'], unique=False)
    # ### end Alembic commands ###
