"""add organizer fields

Revision ID: 5ae8cfd7bca8
Revises: 6562f9b20ac7
Create Date: 2026-06-02 12:45:48.586131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae8cfd7bca8'
down_revision: Union[str, Sequence[str], None] = '6562f9b20ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('organizer_name', sa.String(), nullable=True))
    op.add_column('workshops', sa.Column('organizer_email', sa.String(), nullable=True))
    op.add_column('workshops', sa.Column('organizer_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'organizer_phone')
    op.drop_column('workshops', 'organizer_email')
    op.drop_column('workshops', 'organizer_name')
    # ### end Alembic commands ###
