"""add show_education show_experience

Revision ID: 70c53c797c67
Revises: 4b8904a8043b
Create Date: 2026-06-24 16:07:27.750508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c53c797c67'
down_revision: Union[str, Sequence[str], None] = '4b8904a8043b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop_registrations')
    op.drop_table('news_post_role_model_links')
    op.drop_table('news_category_links')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('bookmarks')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_mentor_applications_email'), table_name='mentor_applications')
    op.drop_index(op.f('ix_mentor_applications_id'), table_name='mentor_applications')
    op.drop_table('mentor_applications')
    op.drop_table('role_models')
    op.drop_index(op.f('ix_mentors_email'), table_name='mentors')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_mentorship_requests_id'), table_name='mentorship_requests')
    op.drop_table('mentorship_requests')
    op.drop_table('news_posts')
    op.drop_table('news_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('news_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentorship_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('expectations', sa.VARCHAR(), nullable=False),
    sa.Column('skills_to_improve', sa.VARCHAR(), nullable=False),
    sa.Column('cv_file_path', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('agreed_to_sessions', sa.BOOLEAN(), nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_requests_id'), 'mentorship_requests', ['id'], unique=False)
    op.create_table('mentors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('institution', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('city_country', sa.VARCHAR(), nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(), nullable=True),
    sa.Column('academic_title', sa.VARCHAR(), nullable=True),
    sa.Column('field_of_expertise', sa.VARCHAR(), nullable=False),
    sa.Column('years_of_experience', sa.VARCHAR(), nullable=True),
    sa.Column('cv_url', sa.VARCHAR(), nullable=True),
    sa.Column('has_mentoring_experience', sa.BOOLEAN(), nullable=True),
    sa.Column('motivation', sa.VARCHAR(), nullable=True),
    sa.Column('max_mentees', sa.INTEGER(), nullable=True),
    sa.Column('preferred_session_format', sa.VARCHAR(), nullable=True),
    sa.Column('bio', sa.VARCHAR(), nullable=True),
    sa.Column('profile_img_url', sa.VARCHAR(), nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.create_index(op.f('ix_mentors_email'), 'mentors', ['email'], unique=1)
    op.create_table('role_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('stem_field', sa.VARCHAR(), nullable=False),
    sa.Column('institution', sa.VARCHAR(), nullable=False),
    sa.Column('position', sa.VARCHAR(), nullable=False),
    sa.Column('biography', sa.TEXT(), nullable=False),
    sa.Column('achievements', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentor_applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('field_of_expertise', sa.VARCHAR(), nullable=False),
    sa.Column('years_of_experience', sa.INTEGER(), nullable=False),
    sa.Column('linkedin_url', sa.VARCHAR(), nullable=False),
    sa.Column('bio', sa.TEXT(), nullable=False),
    sa.Column('cv_url', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_applications_id'), 'mentor_applications', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_applications_email'), 'mentor_applications', ['email'], unique=1)
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('biography', sa.VARCHAR(), nullable=True),
    sa.Column('field', sa.VARCHAR(), nullable=True),
    sa.Column('avatar', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('deactivated_by', sa.VARCHAR(), nullable=True),
    sa.Column('show_biography', sa.BOOLEAN(), nullable=False),
    sa.Column('show_field', sa.BOOLEAN(), nullable=False),
    sa.Column('show_location', sa.BOOLEAN(), nullable=False),
    sa.Column('languages', sa.VARCHAR(), nullable=True),
    sa.Column('experience', sa.VARCHAR(), nullable=True),
    sa.Column('education', sa.VARCHAR(), nullable=True),
    sa.Column('skills', sa.VARCHAR(), nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(), nullable=True),
    sa.Column('github_url', sa.VARCHAR(), nullable=True),
    sa.Column('twitter_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_model_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_model_id'], ['role_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('faculty', sa.VARCHAR(), nullable=True),
    sa.Column('year_of_study', sa.VARCHAR(), nullable=True),
    sa.Column('areas_of_interest', sa.VARCHAR(), nullable=True),
    sa.Column('has_business_idea', sa.VARCHAR(), nullable=True),
    sa.Column('expectations', sa.VARCHAR(), nullable=True),
    sa.Column('skills_to_improve', sa.VARCHAR(), nullable=True),
    sa.Column('motivational_message', sa.TEXT(), nullable=True),
    sa.Column('preferred_session_format', sa.VARCHAR(), nullable=True),
    sa.Column('session_commitment', sa.BOOLEAN(), nullable=True),
    sa.Column('consent_data', sa.BOOLEAN(), nullable=True),
    sa.Column('consent_evaluation', sa.BOOLEAN(), nullable=True),
    sa.Column('cv_url', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=1)
    op.create_table('news_category_links',
    sa.Column('news_post_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ),
    sa.ForeignKeyConstraint(['news_post_id'], ['news_posts.id'], ),
    sa.PrimaryKeyConstraint('news_post_id', 'category_id')
    )
    op.create_table('news_post_role_model_links',
    sa.Column('news_post_id', sa.INTEGER(), nullable=False),
    sa.Column('role_model_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['news_post_id'], ['news_posts.id'], ),
    sa.ForeignKeyConstraint(['role_model_id'], ['role_models.id'], ),
    sa.PrimaryKeyConstraint('news_post_id', 'role_model_id')
    )
    op.create_table('workshop_registrations',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('workshop_id', sa.INTEGER(), nullable=False),
    sa.Column('registered_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workshop_id')
    )
    # ### end Alembic commands ###
