"""kratak opis promjene

Revision ID: a5defcd6b04a
Revises: 4772fe85838c
Create Date: 2026-05-17 21:05:05.059223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5defcd6b04a'
down_revision: Union[str, Sequence[str], None] = '4772fe85838c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prijava')
    op.drop_table('workshop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('naziv', sa.VARCHAR(), nullable=False),
    sa.Column('kapacitet', sa.INTEGER(), nullable=False),
    sa.Column('slobodna_mjesta', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prijava',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ime', sa.VARCHAR(), nullable=False),
    sa.Column('prezime', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('telefon', sa.VARCHAR(), nullable=False),
    sa.Column('workshop_id', sa.INTEGER(), nullable=False),
    sa.Column('iskustvo_prijasnje', sa.VARCHAR(), nullable=True),
    sa.Column('github_profil', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
