"""add mentor_applications table

Revision ID: c958e29d5795
Revises: 4772fe85838c
Create Date: 2026-05-19 15:05:00.977670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c958e29d5795'
down_revision: Union[str, Sequence[str], None] = '4772fe85838c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('field_of_expertise', sa.String(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('cv_url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reviewing', 'approved', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_applications_email'), 'mentor_applications', ['email'], unique=True)
    op.create_index(op.f('ix_mentor_applications_id'), 'mentor_applications', ['id'], unique=False)
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('city_country', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('academic_title', sa.String(), nullable=True),
    sa.Column('field_of_expertise', sa.String(), nullable=False),
    sa.Column('years_of_experience', sa.String(), nullable=True),
    sa.Column('cv_url', sa.String(), nullable=True),
    sa.Column('has_mentoring_experience', sa.Boolean(), nullable=True),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('max_mentees', sa.Integer(), nullable=True),
    sa.Column('preferred_session_format', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('profile_img_url', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentors_email'), 'mentors', ['email'], unique=True)
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_index(op.f('ix_mentors_email'), table_name='mentors')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_mentor_applications_id'), table_name='mentor_applications')
    op.drop_index(op.f('ix_mentor_applications_email'), table_name='mentor_applications')
    op.drop_table('mentor_applications')
    # ### end Alembic commands ###
