"""u Registration modelu dodano polje user_id koji je strani kljuc iz users

Revision ID: cda93358c898
Revises: 1fef6e80ae08
Create Date: 2026-05-25 11:46:53.326948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda93358c898'
down_revision: Union[str, Sequence[str], None] = '1fef6e80ae08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('previous_experience', sa.String(), nullable=True),
    sa.Column('github_profile', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_id'), 'registration', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_id'), table_name='registration')
    op.drop_table('registration')
    # ### end Alembic commands ###
