"""add privacy fields to profile

Revision ID: d39e76fe1314
Revises: 825ba6253c8e
Create Date: 2026-05-28 23:11:02.619063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39e76fe1314'
down_revision: Union[str, Sequence[str], None] = '825ba6253c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('show_biography', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('profiles', sa.Column('show_field', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('profiles', sa.Column('show_location', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'show_location')
    op.drop_column('profiles', 'show_field')
    op.drop_column('profiles', 'show_biography')
    # ### end Alembic commands ###
