"""add deactivated_by to profiles

Revision ID: dca28dbd03a9
Revises: d39e76fe1314
Create Date: 2026-05-30 22:51:04.834035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dca28dbd03a9'
down_revision: Union[str, Sequence[str], None] = 'd39e76fe1314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('deactivated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'deactivated_by')
    # ### end Alembic commands ###
