"""Dodana news_posts i news_post_role_model_links tabela

Revision ID: f14f0d6ad07c
Revises: 4772fe85838c
Create Date: 2026-05-23 11:24:12.355995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f14f0d6ad07c'
down_revision: Union[str, Sequence[str], None] = '4772fe85838c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_post_role_model_links',
    sa.Column('news_post_id', sa.Integer(), nullable=False),
    sa.Column('role_model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_post_id'], ['news_posts.id'], ),
    sa.ForeignKeyConstraint(['role_model_id'], ['role_models.id'], ),
    sa.PrimaryKeyConstraint('news_post_id', 'role_model_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_post_role_model_links')
    op.drop_table('news_posts')
    # ### end Alembic commands ###
