"""Prosirena baza da podrzava waiting listu funkcionalnost

Revision ID: f4bf505fb176
Revises: 27e8127ef2c0
Create Date: 2026-05-31 19:07:10.100905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4bf505fb176'
down_revision: Union[str, Sequence[str], None] = '27e8127ef2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshop_proposals')
    op.add_column('registration', sa.Column('status', sa.String(), nullable=False))
    op.add_column('registration', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index('idx_workshop_status_created', 'registration', ['workshop_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workshop_status_created', table_name='registration')
    op.drop_column('registration', 'created_at')
    op.drop_column('registration', 'status')
    op.create_table('workshop_proposals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
